Removed YAMM specific custom claims
RomainVialard/FirebaseApp pull request #4
Opened 2018-03-01 13:53 UTC by RomainVialard

2018-03-01 16:01 UTC, JeanRemiDelteil commented on src/Code.gs
> + * @param  {object} optAuthData keypairs of data to be associated to this user (aka custom claims).
Why not "optCustomClaims" ?

2018-03-01 16:05 UTC, JeanRemiDelteil requested changes
It could be useful to correctly validate the custom claims before adding them. (fail if not correct as it's an important matter).

https://firebase.google.com/docs/auth/admin/custom-claims#set_and_validate_custom_user_claims_via_the_admin_sdk

2018-03-02 11:04 UTC, RomainVialard commented on src/Code.gs
> + * @param  {object} optAuthData keypairs of data to be associated to this user (aka custom claims).
Sure

2018-03-08 15:33 UTC, JeanRemiDelteil approved these changes

2018-03-08 15:38 UTC, merged